Enable settings options from variable_types_table, not covered by gui_config
This should bring back all the options missing when using operating
modes non native for currently running firmware,
(for instance Trigger/Cycle for Vauto running on Elite fw variant)
without cluttering menus like all_menu patch. And without visible
but read only options.

Probably fixes osresearch/airbreak/issues/42

diff --git a/patch-airsense b/patch-airsense
--- a/patch-airsense
+++ b/patch-airsense
@@ -35,6 +35,41 @@ check_hash() {
 	fi
 }
 
+find_bytes() {
+    # return values:
+    # 0: single address found (print on stdout)
+    # 1: not found
+    # 2: >1 ocurrences found
+    local hex="$1"
+    perl -0777 -e '
+        my ($file, $hex) = @ARGV;
+
+        open my $fh, "<:raw", $file or exit 1;
+        local $/;
+        my $data = <$fh>;
+
+        my $pattern = pack("H*", $hex);
+
+        my @pos;
+        my $i = 0;
+        while (($i = index($data, $pattern, $i)) != -1) {
+            push @pos, $i;
+            $i++;
+            last if @pos > 1;
+        }
+
+        if (@pos == 1) {
+            print "$pos[0]\n";
+            exit 0;
+        } elsif (@pos > 1) {
+            exit 2;
+        } else {
+            exit 1;
+        }
+    ' "$OUT" "$hex"
+}
+
+
 cp "$IN" "$OUT" || die "$OUT: copy failed"
 
 patch_tamper() {
@@ -219,6 +254,23 @@ gui_config () {
 	done
 }
 
+gui_submenus () {
+    STRUCT_SIZE=0x14
+
+    # 0[67] 00 0B 00 73 01 0C  is first variable in all tested firmwares.
+    if offset=$(find_bytes 0B0073010C) ; then
+        let offset=$offset-2
+
+        # variable list built by comparing bit2 of byte0 of variable_types_table of all available 0401 firmwares
+        for var in 0x0A 0x0B 0x14 0x15 0x1E 0x25 0x26 0x27 0x37 0x38 0x39 0x3A 0x63 0x64 ; do
+            ADDR=$(( offset + var * 0x14 ))
+            printf '\x07\x00' | patch $ADDR
+        done
+    else
+        echo "${FUNCNAME[0]}: variable_types_table not found!"
+    fi
+}
+
 gui_config_all () {
     BUILD_FLAGS=$(( BUILD_FLAGS | (1 << 7) ))
     # Enable more settings and reported values by enabling bit 1 for all config variables
@@ -298,6 +350,7 @@ extra_modes # 8
 extra_menu # 16
 # all_menu # 32
 gui_config # 64
+gui_submenus
 
 asv_unlock_ps_range
 
